# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - right_hand_controller
    - left_hand_controller

  left_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - left_joint_a1
      - left_joint_a2
      - left_joint_a3
      - left_joint_a4
      - left_joint_a5
      - left_joint_a6
      - left_joint_a7
  right_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - right_joint_a1
      - right_joint_a2
      - right_joint_a3
      - right_joint_a4
      - right_joint_a5
      - right_joint_a6
      - right_joint_a7

  right_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - right_hand_to_finger_left

  left_hand_controller:
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - left_hand_to_finger_left
      