planning_plugins:
  - ompl_interface/OMPLPlanner

request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision
  - default_planning_request_adapters/FixWorkspaceBounds
  - default_planning_request_adapters/FixStartStateBounds

response_adapters:
  - default_planning_response_adapters/ValidateSolution
  - default_planning_response_adapters/AddTimeOptimalParameterization

display_invalid_plans: true
publish_intermediate_states: true

ompl:
  planning_time: 20.0  # aumenta il tempo massimo per pianificazione
  simplify_solutions: true
  interpolate: true

planner_configs:
  APSConfigDefault:
    type: geometric::AnytimePathShortening
    shortcut: 1
    hybridize: 1
    max_hybrid_paths: 36
    num_planners: 8
    planners: "RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect"

  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.1
    goal_bias: 0.1

left_arm:
  planner_configs:
    - APSConfigDefault
    - RRTConnectkConfigDefault

right_arm:
  planner_configs:
    - APSConfigDefault
    - RRTConnectkConfigDefault
