# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01

moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager
controller_manager_name: /controller_manager   # <- questo Ã¨ il nodo ros2_control_node

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
left_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - left_joint_a1
    - left_joint_a2
    - left_joint_a3
    - left_joint_a4
    - left_joint_a5
    - left_joint_a6
    - left_joint_a7
right_arm_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - right_joint_a1
    - right_joint_a2  
    - right_joint_a3
    - right_joint_a4
    - right_joint_a5
    - right_joint_a6
    - right_joint_a7
    